# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

source 'https://github.com/CocoaPods/Specs.git'

target "clouddoctorapp" do

pod 'Parse'
pod 'AFNetworking'
pod 'CWStatusBarNotification', '~> 2.2.2'
pod 'PulsingHalo', :git => 'https://github.com/shu223/PulsingHalo.git'

end

target "clouddoctorappTests" do

end
