# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

source 'https://github.com/CocoaPods/Specs.git'

target "clouddoctorapp" do

pod 'AFNetworking'
pod 'CWStatusBarNotification', '~> 2.2.2'

end

target "clouddoctorappTests" do

end

`